service: careshare-backend
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  endpointType: REGIONAL
  environment:
    COGNITO_CLIENT_ID: !Ref CognitoUserPoolClient
    USER_POOL_ID: !Ref CognitoUserPool
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt UsersTable.Arn
            - !GetAtt DonationsTable.Arn
            - !Sub "${DonationsTable.Arn}/index/DonorIndex"
        - Effect: Allow
          Action:
            - cognito-idp:AdminConfirmSignUp
          Resource:
            - !GetAtt CognitoUserPool.Arn
plugins:
  - serverless-esbuild
  - serverless-dynamodb
  - serverless-offline  

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'
    concurrency: 10
    define:
      require.resolve: "undefined"

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true 
    noStart: false 
    
functions:
  register:
    handler: src/auth/register.register
    events:
      - http:
          path: api/auth/register
          method: post
          cors: true

  login:
    handler: src/auth/login.login
    events:
      - http:
          path: api/auth/login
          method: post
          cors: true

  createDonation:
    handler: src/donor/controller.createDonation
    events:
      - http:
          path: api/donor/donations
          method: post
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
  
  getActiveDonations:
    handler: src/donor/controller.getActiveDonations
    events:
      - http:
          path: api/donor/donations/active
          method: get
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  getDonationHistory:
    handler: src/donor/controller.getDonationHistory
    events:
      - http:
          path: api/donor/history
          method: get
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn       

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    DonationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DonationsTable
        AttributeDefinitions:
          - AttributeName: donationId
            AttributeType: S
          - AttributeName: donorId
            AttributeType: S
          - AttributeName: volunteerId
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: donationId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: DonorIndex
            KeySchema:
              - AttributeName: donorId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: VolunteerIndex
            KeySchema:
              - AttributeName: volunteerId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: StatusIndex
            KeySchema:
              - AttributeName: status
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        TimeToLiveSpecification:
          AttributeName: expiryAt
          Enabled: true
        BillingMode: PAY_PER_REQUEST

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: CareShareUserPool
        UsernameAttributes: [email]
        AutoVerifiedAttributes: [email]
        Schema:
          - Name: address
            AttributeDataType: String
            Mutable: true
          - Name: role
            AttributeDataType: String
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: CareShareClient
        UserPoolId: !Ref CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: false