service: careshare-backend
useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-1
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  environment:
    COGNITO_CLIENT_ID: { "Ref": "CognitoUserPoolClient" }
    USER_POOL_ID: { "Ref": "CognitoUserPool" }
    IMAGES_BUCKET: careshare-donation-images-${self:provider.stage}
    USERS_TABLE: UsersTable
    DONATIONS_TABLE: DonationsTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - s3:PutObject
            - s3:GetObject
          Resource:
            - !GetAtt UsersTable.Arn
            - !GetAtt DonationsTable.Arn
            - !Sub "${DonationsTable.Arn}/index/DonorIndex"
            - !Sub "${DonationsTable.Arn}/index/StatusIndex"
            - !Sub "${DonationsTable.Arn}/index/VolunteerIndex"
            - !Sub "${DonationsTable.Arn}/index/ReceiverIndex"
            - !Sub "arn:aws:s3:::careshare-donation-images-${self:provider.stage}/*"
plugins:
  - serverless-esbuild
  - serverless-dynamodb
  - serverless-offline  

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'
    concurrency: 10
    define:
      require.resolve: "undefined"

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true 
    noStart: false 
    
functions:
  register:
    handler: src/auth/register.register
    events:
      - http:
          path: api/auth/register
          method: post
          cors: true
 
  verifyEmail:
    handler: src/common/controller.verifyEmail
    events:
      - http:
          path: api/auth/verify
          method: post
          cors: true

  login:
    handler: src/auth/login.login
    events:
      - http:
          path: api/auth/login
          method: post
          cors: true

  createDonation:
    handler: src/donor/controller.createDonation
    events:
      - http:
          path: api/donor/donations
          method: post
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
  
  getUploadUrl:
    handler: src/common/controller.getUploadUrl
    events:
      - http:
          path: api/upload-url
          method: get
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  getExpiredDonations:
    handler: src/common/controller.getExpiredDonations
    events:
      - http:
          path: api/donations/expired
          method: get
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  getUserData:
    handler: src/common/controller.getUserData
    events:
      - http:
          path: api/users/profile
          method: get
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  updateUserData:
    handler: src/common/controller.updateUserData
    events:
      - http:
          path: api/users/profile
          method: put
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  getDonationHistory:
    handler: src/common/controller.getDonationHistory
    events:
      - http:
          path: api/donations/history
          method: get
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  getAllDonations:
    handler: src/donor/controller.getAllDonations
    events:
      - http:
          path: api/donor/donations/all
          method: get
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn


  getVolunteerFeed:
    handler: src/volunteer/controller.getVolunteerFeed
    events:
      - http:
          path: api/volunteer/feed
          method: get
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  claimDonation:
    handler: src/volunteer/controller.claimDonation
    events:
      - http:
          path: api/volunteer/donations/{id}/claim
          method: post
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn         

  getOngoingTasks:
    handler: src/volunteer/controller.getOngoingTasks
    events:
      - http:
          path: api/volunteer/tasks/ongoing
          method: get
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  pickupDonation:
    handler: src/volunteer/controller.pickupDonation
    events:
      - http:
          path: api/volunteer/tasks/{id}/pickup
          method: post
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  getVolunteerInventory:
    handler: src/volunteer/controller.getVolunteerInventory
    events:
      - http:
          path: api/volunteer/inventory
          method: get
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  getLiveFeed:
    handler: src/receiver/controller.getLiveFeed
    events:
      - http:
          path: api/receiver/live-feed
          method: get
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  requestDonation:
    handler: src/receiver/controller.requestDonation
    events:
      - http:
          path: api/receiver/donations/{id}/request
          method: post
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  getPendingRequests:
    handler: src/receiver/controller.getPendingRequests
    events:
      - http:
          path: api/receiver/requests/pending
          method: get
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  getReceiverHub:
    handler: src/receiver/controller.getReceiverHub
    events:
      - http:
          path: api/receiver/hub
          method: get
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn


  expireDonations:
    handler: src/receiver/controller.expireDonations
    events:
      - http:
          path: api/receiver/donations/expire
          method: post
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn
  
  confirmRequest:
    handler: src/volunteer/controller.confirmRequest
    events:
      - http:
          path: api/volunteer/inventory/{id}/confirm-request
          method: post
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  cancelRequest:
    handler: src/volunteer/controller.cancelRequest
    events:
      - http:
          path: api/volunteer/donations/{id}/cancel
          method: post
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn

  deliverDonation:
    handler: src/volunteer/controller.deliverDonation
    events:
      - http:
          path: api/volunteer/inventory/{id}/deliver
          method: post
          cors: true
          authorizer:
            name: cognitoAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt CognitoUserPool.Arn


resources:
  Resources:
    DonationImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: careshare-donation-images-${self:provider.stage}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    DonationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DonationsTable
        AttributeDefinitions:
          - AttributeName: donationId
            AttributeType: S
          - AttributeName: donorId
            AttributeType: S
          - AttributeName: volunteerId
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: receiverId
            AttributeType: S
        KeySchema:
          - AttributeName: donationId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: DonorIndex
            KeySchema:
              - AttributeName: donorId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: VolunteerIndex
            KeySchema:
              - AttributeName: volunteerId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: StatusIndex
            KeySchema:
              - AttributeName: status
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: ReceiverIndex
            KeySchema:
              - AttributeName: receiverId
                KeyType: HASH
            Projection:
              ProjectionType: ALL 

        BillingMode: PAY_PER_REQUEST

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: CareShareUserPool
        UsernameAttributes: [email]
        AutoVerifiedAttributes: [email]
        Schema:
          - Name: email
            AttributeDataType: String
            Required: true
            Mutable: true
          - Name: role
            AttributeDataType: String
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: CareShareClient
        UserPoolId: !Ref CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: false